### ISSUE TITLE
the fonts don't change

### ISSUE THREAD

**Issue by renilbabu03** [braver/fonts#48] opened 2016-12-31 18:15 UTC
the fonts are not changing from the settings...don't know what to do

**Comment by braver** [comment] 2017-01-02 19:19
@renilbabu03 have you tried restarting Atom?

**Comment by briankc** [comment] 2017-01-05 05:31
I had the same issue here (running on Windows) until I restarted Atom.

**Comment by braver** [comment] 2017-01-05 20:30
Ok, labelling it as dupe of #33.

**Closed by braver** 2017-01-05 20:30 UTC
