### ISSUE TITLE
Installing “fonts@3.13.0” failed

### ISSUE THREAD

**Issue by thien0709** [braver/fonts#103] opened 2021-06-05 03:34 UTC
[
[]([]([]([]([](![image](https://user-images.githubusercontent.com/85043649/120878885-a3238d00-c5e9-11eb-8047-a27aa531f94e.png))))))
](url)

**Comment by lierdakil** [comment] 2021-06-05 09:12
Probably a duplicate of #97. Feel free to correct me if I'm wrong.

**Closed as completed by lierdakil** 2021-06-05 09:12 UTC
Labels: duplicate

**Comment by thien0709** [comment] 2021-06-06 10:28
what can i do to install

**Comment by lierdakil** [comment] 2021-06-06 10:50
TL;DR, most probably, node messed up, put a corrupted download in the download cache, and is now silently refusing to re-download. [This comment](https://github.com/braver/fonts/issues/97#issuecomment-631479472) claims cleaning up `~/.atom/.apm` and `~/.atom/.npm`  fixed the issue. (`~/.atom` is `%userprofile%\.atom\` on Windows, i.e. `C:\Users\yourusername\.atom`)

Alternatively, you can manually download/install from repo as per https://github.com/braver/fonts/issues/97#issuecomment-636774425, but you'll probably lose automatic updates.
