### ISSUE TITLE
Can you move the Preview *above* the select

### ISSUE THREAD

**Issue by crayfishuk** [braver/fonts#38] opened 2016-09-23 12:33 UTC
The select box obscures the Preview box. It would be better to have it above the Select, because you can then cycle through the fonts using the up/down key seeing the previews change...

It's a bit of a PITA at the moment... :-)

**Comment by braver** [comment] 2016-09-23 12:34
Duplicate of #36

**Closed by braver** 2016-09-23 12:34 UTC

**Comment by braver** [comment] 2016-09-23 12:38
I know it's a bit of a pain, but putting it above the select doesn't solve it in all cases either.

**Comment by crayfishuk** [comment] 2016-09-23 12:39
Doh! - looked through the Issues twice before raising this one. More coffee needed...

**Comment by braver** [comment] 2016-09-23 12:40
> More coffee needed...

Always!
